variable "vpc_id" {}
variable "app_name" {}
variable "ami" {}
variable "instance_type" {}
variable "subnet_id" {}
variable "key_name" {}
variable "instance_profile" {}
variable "guid" {}
variable "asset_id" {}
variable "public_subnet" {}
